### ISSUE TITLE
login functionality

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectC_Group12#1]
Hey guys,

do you need login functionality for the character-location add functionality?

Greets 
Yasar

**Comment by sacdallago** [comment]
Hi @yashha ; as **you** do you mean us mentors? :smile:

**Comment by yashha** [comment]
@sacdallago I don't know maybe the group members know this.
But yea probably :D
I feel like in all my questions I should put this "@sacdallago" ;)

**Comment by sacdallago** [comment]
ahah @yashha I, on the other hand, feel like in every question there is a little @sacdallago hidden :laughing:
Btw @yashha there is another team (6) which is working on **C**, you might want to ask them too as they are far closer to completion to their task :)

I personally think that implementing a user model without implementing an authority model (in this case) is equal as not implementing a user model at all (because being allowed to assign locations just because one has a username, doesn't guarantee accuracy of data). If, on the other hand, there is also a authority/group model, like: read only / curators / admins, than it makes sense to implement it via login.

So: careful about this.

You can chose not to implement the user/auth models, but then your data is gonna suffer from trolls/accuracy.

Hope I was clear,
Cheers

**Comment by yashha** [comment]
@sacdallago We don't really need a authority model, we only need a way to restrict the add functionality to specific users. So we should probably just add an extra admin page with username/password. Would that be ok?

**Comment by sacdallago** [comment]
@yashha should work. Nice workaround! :dancer:

**Comment by AlexBeischl** [comment]
Hi I'm from Team 10,

we didn't add a Usermodel as we don't need one. As far as we understood, we provide the data and a working map with UI for the characters, like described on the Rostlabpage (outcome) and Project F integrates it into the whole project. Therefore, our teams implementation doesn't require a Usermodel.

**Comment by yashha** [comment]
@AlexBeischl I stumbled upon this:

> Easy user interface to add more characters-locations associations. Use autocomplete when entering a new character name to recreate its locations on the map.

This needs to be protected against random users. So you need an extra map or an additional input, that you get access through an admin interface :)

**Comment by mbandle** [comment]
I don't know whether it means the admin can provide new data or you can click on a person and it loads the data from the DB. 
So recreate would either mean the admin generates the data or the data is loaded and showed to the user. 

How do we have to understand this point? @sacdallago

**Comment by sacdallago** [comment]
@yashha is right about the point on the RostLab page. Premise: I didn't write that.
Logically @AlexBeischl is right: You should provide something like a library, so implementing already a security layer is an overkill. But this goes beyond what I can say.
@gyachdav and @goldbergtatyana have the last word here, so I forwarded your question to them and they will respond (or I on their behalf) as soon as possible.

**Comment by sacdallago** [comment]
OK, so we all got it wrong and I'm sorry for that!
 - No login
 - No: user can add _new positions_ for characters

The only thing that originally wanted to be highlighted with that point is: users should be able to write some character's name in an input field and the input field should autocomplete. Once the user has selected a character, the path the character has walked should appear on the map. If then the user searches and selects another character, the path of this character will **overlay** with the path of the previously selected character, ASO.

Hope everything is clear now :dancer:

**Comment by AlexBeischl** [comment]
:+1:  so we don't have to make our editor look fancy :)
